# USING MARS WEB SCRAPING HOMEWORK AS A REFERENCE SO USE WHAT NEED FROM MARS HW.

In [7]:
import pandas as pd

In [8]:
# URL of page to be scraped
url = 'http://www.alcoholcontents.com/liquor/'

In [9]:
abv_table = pd.read_html(url)
abv_table

[              Liquor / Cocktail / Liqueur  % Alc (ABV)    Cal
 0                                Advocaat           17    NaN
 1                              Aftershock           30    NaN
 2            Aftershock Cinnamon Schnapps           40  103.0
 3    Aftershock Cool Citrus Mint Schnapps           40   72.0
 4                             Aguardiente           30    NaN
 ..                                    ...          ...    ...
 114                       Wallace Liqueur           35    NaN
 115                             Xtabentún           40    NaN
 116                     Yellow Chartreuse           40    NaN
 117                        Yellow Curaçao           31    NaN
 118                            Yukon Jack           50   69.0

 [119 rows x 3 columns]]

In [10]:
abv_df = abv_table[0]
abv_df.head(20)

             Liquor / Cocktail / Liqueur  % Alc (ABV)    Cal
0                               Advocaat           17    NaN
1                             Aftershock           30    NaN
2           Aftershock Cinnamon Schnapps           40  103.0
3   Aftershock Cool Citrus Mint Schnapps           40   72.0
4                            Aguardiente           30    NaN
5                                Amadeus            5    NaN
6                               Amaretto           28  110.0
7                    Amaretto Di Saronno           28  110.0
8                                  Amaro           17    NaN
9                                Amarula           17    NaN
10                     American Schnapps           40    NaN
11                         Anis del Toro           30    NaN
12                              Anisette           30  100.0
13                                  Arak           50    NaN
14                          Ashanti Gold           17    NaN
15                                 Aurum           40  103.0
16                   Baileys Irish Cream           17  117.0
17                            Bärenjäger           35  103.0
18                            Becherovka           38  135.0
19                                Beirão           22    NaN

In [11]:
# Remove Cal column
abv_df = df.drop(['Cal'], axis=1)
abv_df.head()

            Liquor / Cocktail / Liqueur  % Alc (ABV)
0                              Advocaat           17
1                            Aftershock           30
2          Aftershock Cinnamon Schnapps           40
3  Aftershock Cool Citrus Mint Schnapps           40
4                           Aguardiente           30

In [12]:
# Add Common Spirits list to dataframe in ascending order (alphabetical); getting the mean of the abv range.
common_spirits = [{"Liquor / Cocktail / Liqueur": "Absinthe", "% Alc (ABV)": "0"},
                {"Liquor / Cocktail / Liqueur": "Baijiu", "% Alc (ABV)": "0"},
                {"Liquor / Cocktail / Liqueur": "Bourbon", "% Alc (ABV)": "51-79"},
                {"Liquor / Cocktail / Liqueur": "Brandy", "% Alc (ABV)": "40-45"},
                {"Liquor / Cocktail / Liqueur": "Everclear", "% Alc (ABV)": "75-95"},
                {"Liquor / Cocktail / Liqueur": "Gin", "% Alc (ABV)": "37.5"},
                {"Liquor / Cocktail / Liqueur": "Grappa", "% Alc (ABV)": "0"},
                {"Liquor / Cocktail / Liqueur": "Rum", "% Alc (ABV)": "37.5-57"},
                {"Liquor / Cocktail / Liqueur": "Sake", "% Alc (ABV)": "14-16"},
                {"Liquor / Cocktail / Liqueur": "Tequila", "% Alc (ABV)": "40-50"},
                {"Liquor / Cocktail / Liqueur": "Vodka", "% Alc (ABV)": "35-50"},
                {"Liquor / Cocktail / Liqueur": "Whisky", "% Alc (ABV)": "40-53.3"},
                {"Liquor / Cocktail / Liqueur": "German Schnapps", "% Alc (ABV)": "20-40"}]

spirits_df = pd.DataFrame(common_spirits)
spirits_df

   Liquor / Cocktail / Liqueur % Alc (ABV)
0                     Absinthe           0
1                       Baijiu           0
2                      Bourbon       51-79
3                       Brandy       40-45
4                    Everclear       75-95
5                          Gin        37.5
6                       Grappa           0
7                          Rum     37.5-57
8                         Sake       14-16
9                      Tequila       40-50
10                       Vodka       35-50
11                      Whisky     40-53.3
12             German Schnapps       20-40

In [27]:
# Merge spirits_df and abv_df
merge_df = pd.merge(abv_df, spirits_df, on="Liquor / Cocktail / Liqueur", how="outer")
merge_df

              Liquor / Cocktail / Liqueur  % Alc (ABV)_x % Alc (ABV)_y
0                                Advocaat           17.0           NaN
1                              Aftershock           30.0           NaN
2            Aftershock Cinnamon Schnapps           40.0           NaN
3    Aftershock Cool Citrus Mint Schnapps           40.0           NaN
4                             Aguardiente           30.0           NaN
..                                    ...            ...           ...
127                                  Sake            NaN         14-16
128                               Tequila            NaN         40-50
129                                 Vodka            NaN         35-50
130                                Whisky            NaN       40-53.3
131                       German Schnapps            NaN         20-40

[132 rows x 3 columns]

In [20]:
# Sort ascending
abv_sort_df = merge_df.sort_values("Liquor / Cocktail / Liqueur")
abv_sort_df.head(20)

              Liquor / Cocktail / Liqueur  % Alc (ABV)_x % Alc (ABV)_y
119                              Absinthe            NaN             0
0                                Advocaat           17.0           NaN
1                              Aftershock           30.0           NaN
2            Aftershock Cinnamon Schnapps           40.0           NaN
3    Aftershock Cool Citrus Mint Schnapps           40.0           NaN
4                             Aguardiente           30.0           NaN
5                                 Amadeus            5.0           NaN
6                                Amaretto           28.0           NaN
7                     Amaretto Di Saronno           28.0           NaN
8                                   Amaro           17.0           NaN
9                                 Amarula           17.0           NaN
10                      American Schnapps           40.0           NaN
11                          Anis del Toro           30.0           NaN
12                               Anisette           30.0           NaN
13                                   Arak           50.0           NaN
14                           Ashanti Gold           17.0           NaN
15                                  Aurum           40.0           NaN
120                                Baijiu            NaN             0
16                    Baileys Irish Cream           17.0           NaN
18                             Becherovka           38.0           NaN

In [21]:
# Dataframe to HTML
abv_html_table = abv_sort_df.to_html()
abv_html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Liquor / Cocktail / Liqueur</th>\n      <th>% Alc (ABV)_x</th>\n      <th>% Alc (ABV)_y</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>119</th>\n      <td>Absinthe</td>\n      <td>NaN</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Advocaat</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Aftershock</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Aftershock Cinnamon Schnapps</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Aftershock Cool Citrus Mint Schnapps</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Aguardiente</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Amadeus</td>\n      <td>5.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Amaretto</td>\n      <td>28.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Amaretto Di Saronno</td>\n      <td>28.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Amaro</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Amarula</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>American Schnapps</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Anis del Toro</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Anisette</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Arak</td>\n      <td>50.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Ashanti Gold</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Aurum</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>120</th>\n      <td>Baijiu</td>\n      <td>NaN</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Baileys Irish Cream</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Becherovka</td>\n      <td>38.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Beirão</td>\n      <td>22.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Benedictine</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Blue Curaçao</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>121</th>\n      <td>Bourbon</td>\n      <td>NaN</td>\n      <td>51-79</td>\n    </tr>\n    <tr>\n      <th>122</th>\n      <td>Brandy</td>\n      <td>NaN</td>\n      <td>40-45</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Bärenjäger</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Calisay</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Canton</td>\n      <td>28.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>Chambord</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>Chartreuse</td>\n      <td>55.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>Cherry Heering</td>\n      <td>22.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>Cloudberry Liqueur</td>\n      <td>25.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>Coconut Rum</td>\n      <td>21.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>Cointreau</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>Crème de Banane</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>Crème de Cacao</td>\n      <td>25.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>Crème de Cassis</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>Crème de Cerise</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>Crème de Menthe</td>\n      <td>25.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>35</th>\n      <td>Crème de Myrtille</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>Crème de Noyaux</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>Crème de Rose</td>\n      <td>18.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>38</th>\n      <td>Crème de Violette</td>\n      <td>25.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>39</th>\n      <td>Crème de Y\'vette</td>\n      <td>28.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>40</th>\n      <td>Curaçao</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>41</th>\n      <td>Cynar</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>42</th>\n      <td>Damiana</td>\n      <td>50.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>43</th>\n      <td>Destinée</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>44</th>\n      <td>Drambuie</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>45</th>\n      <td>Drumgray Highland Cream Liqueur</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>46</th>\n      <td>Dry Orange Curaçao</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>47</th>\n      <td>Durango</td>\n      <td>9.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>123</th>\n      <td>Everclear</td>\n      <td>NaN</td>\n      <td>75-95</td>\n    </tr>\n    <tr>\n      <th>48</th>\n      <td>Framboise</td>\n      <td>5.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>49</th>\n      <td>Frangelico</td>\n      <td>24.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>50</th>\n      <td>Frigola</td>\n      <td>25.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>51</th>\n      <td>Galliano</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>131</th>\n      <td>German Schnapps</td>\n      <td>NaN</td>\n      <td>20-40</td>\n    </tr>\n    <tr>\n      <th>124</th>\n      <td>Gin</td>\n      <td>NaN</td>\n      <td>37.5</td>\n    </tr>\n    <tr>\n      <th>52</th>\n      <td>Godiva Chocolate Liqueurs</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>53</th>\n      <td>Goldschläger</td>\n      <td>44.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>54</th>\n      <td>Goldwasser</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>55</th>\n      <td>Grand Mariner</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>125</th>\n      <td>Grappa</td>\n      <td>NaN</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>56</th>\n      <td>Green Chartreuse</td>\n      <td>55.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>57</th>\n      <td>Green Curaçao</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>58</th>\n      <td>Herbsaint</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>59</th>\n      <td>Highland Mist</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>60</th>\n      <td>Hpnotiq</td>\n      <td>18.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>61</th>\n      <td>Irish Cream</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>62</th>\n      <td>Izarra</td>\n      <td>48.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>63</th>\n      <td>Jägermeister</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>64</th>\n      <td>Kahlúa</td>\n      <td>27.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>65</th>\n      <td>Krupnik</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>66</th>\n      <td>Kümmel</td>\n      <td>38.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>67</th>\n      <td>Lazzaroni Amaretto</td>\n      <td>24.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>68</th>\n      <td>Licor 43</td>\n      <td>31.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>69</th>\n      <td>Limoncello</td>\n      <td>32.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>70</th>\n      <td>Malibu</td>\n      <td>24.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>71</th>\n      <td>Maraschino</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>72</th>\n      <td>Mastica</td>\n      <td>47.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>73</th>\n      <td>Melon Liqueur</td>\n      <td>23.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>74</th>\n      <td>Metaxa</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>75</th>\n      <td>Midori</td>\n      <td>23.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>76</th>\n      <td>Mozart Chocolate Liqueurs</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>77</th>\n      <td>Nocello</td>\n      <td>24.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>78</th>\n      <td>Nocino</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>79</th>\n      <td>Oghi</td>\n      <td>53.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>80</th>\n      <td>Ouzo</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>81</th>\n      <td>Parfait Amour</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>82</th>\n      <td>Pastis</td>\n      <td>43.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>83</th>\n      <td>Patxaran</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>84</th>\n      <td>Peach Liqueur</td>\n      <td>23.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>85</th>\n      <td>Pecher Mignon</td>\n      <td>18.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>86</th>\n      <td>Pineau des Charentes</td>\n      <td>15.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>87</th>\n      <td>Pisang Ambon</td>\n      <td>21.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>88</th>\n      <td>Ponche Caribe</td>\n      <td>11.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>89</th>\n      <td>Ponche Crema</td>\n      <td>15.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>90</th>\n      <td>Ponche Diva</td>\n      <td>10.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>91</th>\n      <td>Ponche Kuba</td>\n      <td>9.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>92</th>\n      <td>Prunelle</td>\n      <td>15.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>93</th>\n      <td>Raki</td>\n      <td>45.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>94</th>\n      <td>Red Curaçao</td>\n      <td>31.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>95</th>\n      <td>Rock and rye</td>\n      <td>27.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>126</th>\n      <td>Rum</td>\n      <td>NaN</td>\n      <td>37.5-57</td>\n    </tr>\n    <tr>\n      <th>96</th>\n      <td>Rum Tree</td>\n      <td>24.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>97</th>\n      <td>Rumple Minze</td>\n      <td>50.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>98</th>\n      <td>Sabra liqueur</td>\n      <td>27.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>99</th>\n      <td>Saint Brendan\'s</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>127</th>\n      <td>Sake</td>\n      <td>NaN</td>\n      <td>14-16</td>\n    </tr>\n    <tr>\n      <th>100</th>\n      <td>Salmiakkikossu</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>101</th>\n      <td>Sambuca</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>102</th>\n      <td>Sheridan\'s</td>\n      <td>16.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>103</th>\n      <td>Sloe gin</td>\n      <td>26.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>104</th>\n      <td>Southern Comfort</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>105</th>\n      <td>Starbucks Coffee Liqueur</td>\n      <td>20.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>106</th>\n      <td>Starbucks Cream Liqueur</td>\n      <td>15.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>107</th>\n      <td>Strega</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>128</th>\n      <td>Tequila</td>\n      <td>NaN</td>\n      <td>40-50</td>\n    </tr>\n    <tr>\n      <th>108</th>\n      <td>Tia Lusso (with cream)</td>\n      <td>27.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>109</th>\n      <td>Tia Maria</td>\n      <td>27.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>110</th>\n      <td>Triple sec</td>\n      <td>30.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>111</th>\n      <td>Tsipouro</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>112</th>\n      <td>Vandermint</td>\n      <td>26.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>113</th>\n      <td>Vermeer Dutch Chocolate Cream Liqueur</td>\n      <td>17.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>129</th>\n      <td>Vodka</td>\n      <td>NaN</td>\n      <td>35-50</td>\n    </tr>\n    <tr>\n      <th>114</th>\n      <td>Wallace Liqueur</td>\n      <td>35.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>130</th>\n      <td>Whisky</td>\n      <td>NaN</td>\n      <td>40-53.3</td>\n    </tr>\n    <tr>\n      <th>115</th>\n      <td>Xtabentún</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>116</th>\n      <td>Yellow Chartreuse</td>\n      <td>40.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>117</th>\n      <td>Yellow Curaçao</td>\n      <td>31.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>118</th>\n      <td>Yukon Jack</td>\n      <td>50.0</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>'

In [22]:
abv_html_table.replace('\n', '')

'<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Liquor / Cocktail / Liqueur</th>      <th>% Alc (ABV)_x</th>      <th>% Alc (ABV)_y</th>    </tr>  </thead>  <tbody>    <tr>      <th>119</th>      <td>Absinthe</td>      <td>NaN</td>      <td>0</td>    </tr>    <tr>      <th>0</th>      <td>Advocaat</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>1</th>      <td>Aftershock</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>2</th>      <td>Aftershock Cinnamon Schnapps</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>3</th>      <td>Aftershock Cool Citrus Mint Schnapps</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>4</th>      <td>Aguardiente</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>5</th>      <td>Amadeus</td>      <td>5.0</td>      <td>NaN</td>    </tr>    <tr>      <th>6</th>      <td>Amaretto</td>      <td>28.0</td>      <td>NaN</td>    </tr>    <tr>      <th>7</th>      <td>Amaretto Di Saronno</td>      <td>28.0</td>      <td>NaN</td>    </tr>    <tr>      <th>8</th>      <td>Amaro</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>9</th>      <td>Amarula</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>10</th>      <td>American Schnapps</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>11</th>      <td>Anis del Toro</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>12</th>      <td>Anisette</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>13</th>      <td>Arak</td>      <td>50.0</td>      <td>NaN</td>    </tr>    <tr>      <th>14</th>      <td>Ashanti Gold</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>15</th>      <td>Aurum</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>120</th>      <td>Baijiu</td>      <td>NaN</td>      <td>0</td>    </tr>    <tr>      <th>16</th>      <td>Baileys Irish Cream</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>18</th>      <td>Becherovka</td>      <td>38.0</td>      <td>NaN</td>    </tr>    <tr>      <th>19</th>      <td>Beirão</td>      <td>22.0</td>      <td>NaN</td>    </tr>    <tr>      <th>20</th>      <td>Benedictine</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>21</th>      <td>Blue Curaçao</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>121</th>      <td>Bourbon</td>      <td>NaN</td>      <td>51-79</td>    </tr>    <tr>      <th>122</th>      <td>Brandy</td>      <td>NaN</td>      <td>40-45</td>    </tr>    <tr>      <th>17</th>      <td>Bärenjäger</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>22</th>      <td>Calisay</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>23</th>      <td>Canton</td>      <td>28.0</td>      <td>NaN</td>    </tr>    <tr>      <th>24</th>      <td>Chambord</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>25</th>      <td>Chartreuse</td>      <td>55.0</td>      <td>NaN</td>    </tr>    <tr>      <th>26</th>      <td>Cherry Heering</td>      <td>22.0</td>      <td>NaN</td>    </tr>    <tr>      <th>27</th>      <td>Cloudberry Liqueur</td>      <td>25.0</td>      <td>NaN</td>    </tr>    <tr>      <th>28</th>      <td>Coconut Rum</td>      <td>21.0</td>      <td>NaN</td>    </tr>    <tr>      <th>29</th>      <td>Cointreau</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>30</th>      <td>Crème de Banane</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>31</th>      <td>Crème de Cacao</td>      <td>25.0</td>      <td>NaN</td>    </tr>    <tr>      <th>32</th>      <td>Crème de Cassis</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>33</th>      <td>Crème de Cerise</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>34</th>      <td>Crème de Menthe</td>      <td>25.0</td>      <td>NaN</td>    </tr>    <tr>      <th>35</th>      <td>Crème de Myrtille</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>36</th>      <td>Crème de Noyaux</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>37</th>      <td>Crème de Rose</td>      <td>18.0</td>      <td>NaN</td>    </tr>    <tr>      <th>38</th>      <td>Crème de Violette</td>      <td>25.0</td>      <td>NaN</td>    </tr>    <tr>      <th>39</th>      <td>Crème de Y\'vette</td>      <td>28.0</td>      <td>NaN</td>    </tr>    <tr>      <th>40</th>      <td>Curaçao</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>41</th>      <td>Cynar</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>42</th>      <td>Damiana</td>      <td>50.0</td>      <td>NaN</td>    </tr>    <tr>      <th>43</th>      <td>Destinée</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>44</th>      <td>Drambuie</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>45</th>      <td>Drumgray Highland Cream Liqueur</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>46</th>      <td>Dry Orange Curaçao</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>47</th>      <td>Durango</td>      <td>9.0</td>      <td>NaN</td>    </tr>    <tr>      <th>123</th>      <td>Everclear</td>      <td>NaN</td>      <td>75-95</td>    </tr>    <tr>      <th>48</th>      <td>Framboise</td>      <td>5.0</td>      <td>NaN</td>    </tr>    <tr>      <th>49</th>      <td>Frangelico</td>      <td>24.0</td>      <td>NaN</td>    </tr>    <tr>      <th>50</th>      <td>Frigola</td>      <td>25.0</td>      <td>NaN</td>    </tr>    <tr>      <th>51</th>      <td>Galliano</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>131</th>      <td>German Schnapps</td>      <td>NaN</td>      <td>20-40</td>    </tr>    <tr>      <th>124</th>      <td>Gin</td>      <td>NaN</td>      <td>37.5</td>    </tr>    <tr>      <th>52</th>      <td>Godiva Chocolate Liqueurs</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>53</th>      <td>Goldschläger</td>      <td>44.0</td>      <td>NaN</td>    </tr>    <tr>      <th>54</th>      <td>Goldwasser</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>55</th>      <td>Grand Mariner</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>125</th>      <td>Grappa</td>      <td>NaN</td>      <td>0</td>    </tr>    <tr>      <th>56</th>      <td>Green Chartreuse</td>      <td>55.0</td>      <td>NaN</td>    </tr>    <tr>      <th>57</th>      <td>Green Curaçao</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>58</th>      <td>Herbsaint</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>59</th>      <td>Highland Mist</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>60</th>      <td>Hpnotiq</td>      <td>18.0</td>      <td>NaN</td>    </tr>    <tr>      <th>61</th>      <td>Irish Cream</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>62</th>      <td>Izarra</td>      <td>48.0</td>      <td>NaN</td>    </tr>    <tr>      <th>63</th>      <td>Jägermeister</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>64</th>      <td>Kahlúa</td>      <td>27.0</td>      <td>NaN</td>    </tr>    <tr>      <th>65</th>      <td>Krupnik</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>66</th>      <td>Kümmel</td>      <td>38.0</td>      <td>NaN</td>    </tr>    <tr>      <th>67</th>      <td>Lazzaroni Amaretto</td>      <td>24.0</td>      <td>NaN</td>    </tr>    <tr>      <th>68</th>      <td>Licor 43</td>      <td>31.0</td>      <td>NaN</td>    </tr>    <tr>      <th>69</th>      <td>Limoncello</td>      <td>32.0</td>      <td>NaN</td>    </tr>    <tr>      <th>70</th>      <td>Malibu</td>      <td>24.0</td>      <td>NaN</td>    </tr>    <tr>      <th>71</th>      <td>Maraschino</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>72</th>      <td>Mastica</td>      <td>47.0</td>      <td>NaN</td>    </tr>    <tr>      <th>73</th>      <td>Melon Liqueur</td>      <td>23.0</td>      <td>NaN</td>    </tr>    <tr>      <th>74</th>      <td>Metaxa</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>75</th>      <td>Midori</td>      <td>23.0</td>      <td>NaN</td>    </tr>    <tr>      <th>76</th>      <td>Mozart Chocolate Liqueurs</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>77</th>      <td>Nocello</td>      <td>24.0</td>      <td>NaN</td>    </tr>    <tr>      <th>78</th>      <td>Nocino</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>79</th>      <td>Oghi</td>      <td>53.0</td>      <td>NaN</td>    </tr>    <tr>      <th>80</th>      <td>Ouzo</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>81</th>      <td>Parfait Amour</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>82</th>      <td>Pastis</td>      <td>43.0</td>      <td>NaN</td>    </tr>    <tr>      <th>83</th>      <td>Patxaran</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>84</th>      <td>Peach Liqueur</td>      <td>23.0</td>      <td>NaN</td>    </tr>    <tr>      <th>85</th>      <td>Pecher Mignon</td>      <td>18.0</td>      <td>NaN</td>    </tr>    <tr>      <th>86</th>      <td>Pineau des Charentes</td>      <td>15.0</td>      <td>NaN</td>    </tr>    <tr>      <th>87</th>      <td>Pisang Ambon</td>      <td>21.0</td>      <td>NaN</td>    </tr>    <tr>      <th>88</th>      <td>Ponche Caribe</td>      <td>11.0</td>      <td>NaN</td>    </tr>    <tr>      <th>89</th>      <td>Ponche Crema</td>      <td>15.0</td>      <td>NaN</td>    </tr>    <tr>      <th>90</th>      <td>Ponche Diva</td>      <td>10.0</td>      <td>NaN</td>    </tr>    <tr>      <th>91</th>      <td>Ponche Kuba</td>      <td>9.0</td>      <td>NaN</td>    </tr>    <tr>      <th>92</th>      <td>Prunelle</td>      <td>15.0</td>      <td>NaN</td>    </tr>    <tr>      <th>93</th>      <td>Raki</td>      <td>45.0</td>      <td>NaN</td>    </tr>    <tr>      <th>94</th>      <td>Red Curaçao</td>      <td>31.0</td>      <td>NaN</td>    </tr>    <tr>      <th>95</th>      <td>Rock and rye</td>      <td>27.0</td>      <td>NaN</td>    </tr>    <tr>      <th>126</th>      <td>Rum</td>      <td>NaN</td>      <td>37.5-57</td>    </tr>    <tr>      <th>96</th>      <td>Rum Tree</td>      <td>24.0</td>      <td>NaN</td>    </tr>    <tr>      <th>97</th>      <td>Rumple Minze</td>      <td>50.0</td>      <td>NaN</td>    </tr>    <tr>      <th>98</th>      <td>Sabra liqueur</td>      <td>27.0</td>      <td>NaN</td>    </tr>    <tr>      <th>99</th>      <td>Saint Brendan\'s</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>127</th>      <td>Sake</td>      <td>NaN</td>      <td>14-16</td>    </tr>    <tr>      <th>100</th>      <td>Salmiakkikossu</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>101</th>      <td>Sambuca</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>102</th>      <td>Sheridan\'s</td>      <td>16.0</td>      <td>NaN</td>    </tr>    <tr>      <th>103</th>      <td>Sloe gin</td>      <td>26.0</td>      <td>NaN</td>    </tr>    <tr>      <th>104</th>      <td>Southern Comfort</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>105</th>      <td>Starbucks Coffee Liqueur</td>      <td>20.0</td>      <td>NaN</td>    </tr>    <tr>      <th>106</th>      <td>Starbucks Cream Liqueur</td>      <td>15.0</td>      <td>NaN</td>    </tr>    <tr>      <th>107</th>      <td>Strega</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>128</th>      <td>Tequila</td>      <td>NaN</td>      <td>40-50</td>    </tr>    <tr>      <th>108</th>      <td>Tia Lusso (with cream)</td>      <td>27.0</td>      <td>NaN</td>    </tr>    <tr>      <th>109</th>      <td>Tia Maria</td>      <td>27.0</td>      <td>NaN</td>    </tr>    <tr>      <th>110</th>      <td>Triple sec</td>      <td>30.0</td>      <td>NaN</td>    </tr>    <tr>      <th>111</th>      <td>Tsipouro</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>112</th>      <td>Vandermint</td>      <td>26.0</td>      <td>NaN</td>    </tr>    <tr>      <th>113</th>      <td>Vermeer Dutch Chocolate Cream Liqueur</td>      <td>17.0</td>      <td>NaN</td>    </tr>    <tr>      <th>129</th>      <td>Vodka</td>      <td>NaN</td>      <td>35-50</td>    </tr>    <tr>      <th>114</th>      <td>Wallace Liqueur</td>      <td>35.0</td>      <td>NaN</td>    </tr>    <tr>      <th>130</th>      <td>Whisky</td>      <td>NaN</td>      <td>40-53.3</td>    </tr>    <tr>      <th>115</th>      <td>Xtabentún</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>116</th>      <td>Yellow Chartreuse</td>      <td>40.0</td>      <td>NaN</td>    </tr>    <tr>      <th>117</th>      <td>Yellow Curaçao</td>      <td>31.0</td>      <td>NaN</td>    </tr>    <tr>      <th>118</th>      <td>Yukon Jack</td>      <td>50.0</td>      <td>NaN</td>    </tr>  </tbody></table>'

In [23]:
abv_sort_df.to_html('abv_table.html')